services:

  mysql:

    image: mysql:8.0
    container_name: capick-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: capick
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - capick-mysql-data:/var/lib/mysql

volumes:
  capick-mysql-data: