spring:
  application:
    name: BE
    security:
      oauth2:
        client:
          registration:
            kakao:
            naver:

  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: ${DB_USER:capick}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

